# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
    paths:
      - 'R/**'
      - 'man/**'
      - 'vignettes/**'
      - 'README.Rmd'
      - 'inst/WORDLIST'
      - '.github/workflows/spellcheck.yaml'
  pull_request:
    branches: [main, master]
    paths:
      - 'R/**'
      - 'man/**'
      - 'vignettes/**'
      - 'README.Rmd'
      - 'inst/WORDLIST'
      - '.github/workflows/spellcheck.yaml'

name: spellcheck

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::spelling, local::.
          needs: spelling
          cache-version: 2

      - name: Check spelling
        run: |
          results <- spelling::spell_check_package()
          if (nrow(results) > 0) {
            print(results)
            cat("\n")
            cat("::error::Spelling errors found. Please add words to inst/WORDLIST or fix typos.\n")
            quit(status = 1)
          }
        shell: Rscript {0}
